version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    commit-message:
      prefix: "meta-*: "
    schedule:
      interval: "daily"
    groups:
      layers:
        patterns:
          - "poky"
          - "meta-*"
    target-branch: "master-next"
    labels:
      - "dependencies"
      - "automerge"
